# this file shows specific settings for evaluation on each dataset
validate#postprocessing#transforms#0#_disabled_: false
validate#handlers#2#_disabled_: true
validate#evaluator#key_val_metric: null
eval_folder: "/eval/"
ckpt_path: "$@bundle_root + '/models/model.pt'"
label_set: "$list(set([i+1 for i in range(117)]) - set([22, 23, 15, 25, 19, 2, 26, 27, 28, 29, 117]))"
val_label_set: "$list(range(118))"
label_mappings: "${}"
# label_mappings:
#     default:
#       - [1, 25]  # lung tumor
#       - [2, 26]  # pancreatic tumor
#       - [1, 27]  # hepatic vessel
#       - [2, 28]  # hepatic tumor
#       - [1, 29]  # colon tumor
#       - [1, 117]  # bone tumor
#       - [2, 117]  # bone tumor
#       - [10, 1]  # liver
#       - [12, 3]  # spleen
#       - [13, 4]  # pancreas
#       - [15, 30]  # left lung upper lobe
#       - [16, 31]  # left lung lower lobe
#       - [17, 32]  # right lung upper lobe
#       - [18, 33]  # right lung middle lobe
#       - [19, 34]  # right lung lower lobe
#       - [20, 5]  # right kidney
#       - [21, 14]  # left kidney
#       - [22, 71]  # left rib 1
#       - [23, 72]  # left rib 2
#       - [24, 73]
#       - [25, 74]
#       - [26, 75]
#       - [27, 76]
#       - [28, 77]
#       - [29, 79]
#       - [30, 80]
#       - [31, 81]
#       - [32, 82]  # left rib 12
