imports:
- $import scripts
- $import scripts.inference

args:
  run_extract : False
  # input_dir : "/data/amd-data/cera-rpddata/Himeesh DICOM/Folder 1"
  # extracted_dir : "/data/yelena/monaiRPD/extracted_dicom"
  # input_format : "dicom"
  input_dir : "/data/amd-data/cera-rpddata/RPD_Himeesh_v2"
  extracted_dir : "/data/yelena/monaiRPD/extracted_vol"
  input_format : "vol"
  create_dataset : False
  dataset_name : "monai_vol"

  output_dir : "/data/yelena/monaiRPD/output_vol"
  run_inference : False
  create_tables : False

# create visuals
  binary_mask : False
  binary_mask_overlay : False
  instance_mask_overlay : False

inference:
- $scripts.inference.main(@args)