name: premerge-cpu-check

on:
  # code format check for pull requests and the dev branch
  push:
    branches:
      - dev
  pull_request:

concurrency:
  # automatically cancel the previously triggered workflows when there's a newer version
  group: premerge-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  premerge-cpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: cache weekly timestamp
      id: pip-cache
      run: |
        echo "::set-output name=datew::$(date '+%Y-%V')"
    - name: cache for pip
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ steps.pip-cache.outputs.datew }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements-dev.txt
        python -m pip install cffi && python -m pip install pipenv
    - name: check
      run: |
        # clean up temporary files
        $(pwd)/runtests.sh --clean
        df -h
        bash $(pwd)/ci/run_premerge_cpu.sh changed
      shell: bash
