name: premerge-cpu-check

on:
  # code format check for pull requests and the dev branch
  push:
    branches:
      - dev
  pull_request:

concurrency:
  # automatically cancel the previously triggered workflows when there's a newer version
  group: premerge-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  premerge-cpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel wheel-stub
        python -m pip install --upgrade setuptools
    - name: check
      run: |
        # clean up temporary files
        $(pwd)/runtests.sh --clean
        df -h
        bash $(pwd)/ci/run_premerge_cpu.sh changed
      shell: bash
