name: update-model-info

on:
  # schedule:
  # - cron: "0 10 * * *"  # 10:00, everyday
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  pull_request:

jobs:
  build:
    # if: github.ref == 'refs/heads/dev'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: update model info
      run: |
        python -m pip install -r requirements-update-model.txt
        python $(pwd)/ci/update_model_info.py --f ""
      env:
        GITHUB_TOKEN: ${{ secrets.UPDATE_MODEL_TOKEN }}
