name: update-model-info

on:
  pull_request:
    # branches:
    #   - dev
    # types: [closed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    permissions: write
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: update model info
      run: |
        python -m pip install -r requirements.txt
        changes=$(git diff --name-only HEAD^..HEAD -- models)
        changes="models/brats_mri_segmentation"
        if [ ! -z "$changes" ]; then
          python $(pwd)/ci/update_model_info.py --f "$changes"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        username: ${{ secrets.UPDATE_MODEL_USERNAME }}
        email: ${{ secrets.UPDATE_MODEL_EMAIL }}
