name: verify-bundle

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: verify bundle
      run: |
        python -m pip install -r requirements.txt
        changes=$(git diff --name-only HEAD..dev -- models)
        if [ ! -z "$changes" ]; then
          python $(pwd)/ci/verify_bundle.py --f "$changes"
        fi
