name: weekly-tests-cpu

on:
  # weekly tests for existing bundles in release
  schedule:
  - cron: "0 5 * * 0"  # 5:00, every Sunday
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:

jobs:
  get-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: cache weekly timestamp
      id: pip-cache
      run: |
        echo "::set-output name=datew::$(date '+%Y-%V')"
    - name: cache for pip
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ steps.pip-cache.outputs.datew }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements-dev.txt
        python -m pip install cffi && python -m pip install pipenv
    - name: get latest bundle list
      id: get-bundle-list
      run: |
        # clean up temporary files
        $(pwd)/runtests.sh --clean
        list=$(python $(pwd)/ci/get_bundle_list.py)
        echo "$list"
        echo "$list" >> $GITHUB_OUTPUT
      shell: bash
  test-cpu:
    needs: get-list
    strategy:
      matrix:
        bundle: ${{ needs.get-list.steps.get-bundle-list.outputs.list }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: cache weekly timestamp
      id: pip-cache
      run: |
        echo "::set-output name=datew::$(date '+%Y-%V')"
    - name: cache for pip
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ steps.pip-cache.outputs.datew }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install cffi && python -m pip install pipenv
    - name: gcheck
      run: |
        # clean up temporary files
        $(pwd)/runtests.sh --clean
        bash $(pwd)/ci/run_regular_tests_cpu.sh ${{ matrix.bundle }}
      shell: bash
